### ISSUE TITLE
QSH not running from bash

### ISSUE THREAD

**Issue by tools400** [halcyon-tech/code-for-ibmi#69] opened 2021-03-03 08:01 UTC
I receive the above mentioned error message, when I attempt to connect to our IBM i server. There is no further information about the error. So what can I do know? I already checked the server side and I noticed, that there is a SSH connection to my PC:

![image](https://user-images.githubusercontent.com/3110562/109772233-0aeac600-7bfe-11eb-8f37-73daee8b04c9.png)

Successfully connected as clearly indicated by the job log:

![image](https://user-images.githubusercontent.com/3110562/109772315-21911d00-7bfe-11eb-9aba-08a07979ace8.png)

Last but not least, I receive error "Object already exists.  Object is /home/raddatz." when I execute command "mkdir '/home/raddatz'", whereas "IBMi.js" checks for "File exists". Could that be part of the problem?

**Comment by worksofliam** [comment] 2021-03-03 13:07
I doubt the object exists in a problem because we check for that too. 

I will look to add a bit more information.

**Comment by worksofliam** [comment] 2021-03-03 13:18
@tools400 Just released 0.2.2 which should give you some more information in that error window :)

**Comment by tools400** [comment] 2021-03-03 13:36
I assume, that you added the low level error message to the "Not connected" message, right? Not I get the following error message: Not connected to our.server.de! undefined

When I enter a wrong url, I get: Not connected to xour.server.de! getaddrinfo ENOTFOUND xour.server.de
For a wrong user/password it is: Not connected to our.server.de! All configured authe...

So the problem is still not obvious. Connecting to the server via SSH on a GitBash works fine.

**Comment by worksofliam** [comment] 2021-03-03 13:43
Huh!! That is interesting. Let me add something else...

Thanks,
Liam

On 3 Mar 2021, at 08:36, Thomas Raddatz <notifications@github.com> wrote:

﻿

I assume, that you added the low level error message to the "Not connected" message, right? Not I get the following error message: Not connected to our.server.de! undefined

When I enter a wrong url, I get: Not connected to xour.server.de! getaddrinfo ENOTFOUND xour.server.de
For a wrong user/password it is: Not connected to our.server.de! All configured authe...

So the problem is still not obvious. Connecting to the server via SSH on a GitBash works fine.

**Comment by worksofliam** [comment] 2021-03-03 13:47
@tools400 0.2.3 is out which might print another message. When you get it, give it another go.

**Comment by worksofliam** [comment] 2021-03-03 13:50
After a quick review, it looks like the issue might be this call: 

https://github.com/halcyon-tech/code-for-ibmi/blob/master/src/api/IBMi.js#L60

**Comment by worksofliam** [comment] 2021-03-03 22:33
Any update here, @tools400?

**Comment by tools400** [comment] 2021-03-04 05:56
After updating to 0.2.5 the error message changed to "Not connected to our.server.de! bsh: 44771 Abort".

**Comment by worksofliam** [comment] 2021-03-04 13:32
Well, it looks like an issue with your setup probably. Do you have a `.profile` or a `.bashrc`, or `.bash_profile`? Would you mind sharing if you do?

**Comment by tools400** [comment] 2021-03-04 15:12
That is what I have: .bashrc and .profile:

```bash
bash-4.4$ ls -la ~/.bash*
-rw-------    1 raddatz  0              8245 Mar  4 16:07 /home/raddatz/.bash_history
-rwxrwxrwx    1 raddatz  0                30 Mar  4 16:08 /home/raddatz/.bashrc
bash-4.4$ cat ~/.bashrc
PATH=/QOpenSys/pkgs/bin:$PATH
bash-4.4$ ls -la ~/.profile
-rw-r--r--    1 raddatz  0                42 Feb 12 15:24 .profile
bash-4.4$ cat ~/.profile
PATH=/QOpenSys/pkgs/bin:$PATH
export PATH
bash-4.4$
```

**Comment by worksofliam** [comment] 2021-03-04 15:17
@tools400 I am afraid since I can't recreate this, it will have to come down to your debugging of the extension or perhaps some input who has any idea what `bsh: 44771 Abort` could indicate.

Could you run this from your base shell: `echo liblist | /QOpenSys/usr/bin/qsh`? Please share the result here.

**Comment by tools400** [comment] 2021-03-04 15:41
This is the output of Git Bash:

```bash
traddatz@CDDEA050914 MINGW64 /c/Users/traddatz
$ ssh raddatz@our.server.de
raddatz@our.server.de's password:
Executing: .profile
$ bash
Executing: .bashrc
bash-4.4$ echo liblist | /QOpenSys/usr/bin/qsh
bash-4.4$
```

And this is the output of STRQSH:

```bash
  Executing: .profile                 
  Executing: .bashrc                  
  $                                   
> echo liblist | /QOpenSys/usr/bin/qsh
  QSYS2924    SYS                     
  UBMSYS      SYS                     
  QSYS        SYS                     
  QSYS2       SYS                     
  QHLPSYS     SYS                     
  QUSRSYS     SYS                     
  QSHELL      PRD                     
  RADDATZ400  CUR   
...                  
```

**Comment by worksofliam** [comment] 2021-03-04 15:43
Could you also try this from git bash?

```
/QOpenSys/usr/bin/qsh liblist
```

Thanks

**Comment by tools400** [comment] 2021-03-04 15:45
```bash
traddatz@CDDEA050914 MINGW64 /c/Users/traddatz
$ ssh raddatz@our.server.de
raddatz@our.server.de's password:
Executing: .profile
$ bash
Executing: .bashrc
bash-4.4$ echo liblist | /QOpenSys/usr/bin/qsh
bash-4.4$
bash-4.4$
bash-4.4$ /QOpenSys/usr/bin/qsh liblist
bash-4.4$
```

**Comment by worksofliam** [comment] 2021-03-04 15:46
Sorry

I meant `/QOpenSys/usr/bin/qsh -c liblist`!

**Comment by worksofliam** [comment] 2021-03-04 15:48
I think I see the problem. When you were running this command you were not getting any output, but when I run it on a few systems I have, I see the list:

```
bash-4.4$ echo liblist | /QOpenSys/usr/bin/qsh
QSYS        SYS
QSYS2       SYS
QHLPSYS     SYS
QUSRSYS     SYS
QSHELL      PRD
BARRY       CUR
QGPL        USR
QTEMP       USR
```

**Comment by tools400** [comment] 2021-03-04 15:58
The following command produces an output similar to 'liblist':

```bash
bash-4.4$ system 'dsplibl' | egrep -i 'sys|cur|usr' | cut -b1-20
   QSYS2924    SYS
   UBMSYS      SYS
   QSYS        SYS
   QSYS2       SYS
   QHLPSYS     SYS
   QUSRSYS     SYS
   RADDATZ400  CUR
   QTEMP       USR
...
```

Is that worth a try?

**Comment by tools400** [comment] 2021-03-04 16:11
You are correct. The following command (see above) does not produce any output, too:

```bash
bash-4.4$ /QOpenSys/usr/bin/qsh -c liblist
bash-4.4$

```

**Comment by tools400** [comment] 2021-03-04 16:14
Is it possible that somehow stdout is not connected when starting qsh?

**Comment by tools400** [comment] 2021-03-04 16:21
The following sequence works, too. It makes me be believe that somehow stdout is not piped from qsh to bash:

```bash
bash-4.4$ touch ~/out.txt
bash-4.4$ /QOpenSys/usr/bin/qsh -c 'liblist > ~/out.txt'
bash-4.4$ cat ~/out.txt
QSYS2924    SYS
UBMSYS      SYS
QSYS        SYS
QSYS2       SYS
QHLPSYS     SYS
QUSRSYS     SYS
RADDATZ400  CUR
QTEMP       USR
QGPL        USR
bash-4.4$
```

**Comment by worksofliam** [comment] 2021-03-04 16:23
@tools400 

1. What version of the OS are you on?
2. What's your `QCCSID`?
3. Are you using bash from yum?
4. What is your `$PATH`?
5. From bash, are you able to launch QSH (just by calling `/QOpenSys/usr/bin/qsh`) and run `liblist`? Does that return a different result?

**Comment by tools400** [comment] 2021-03-04 17:18
1. OS 7.3
2. 273/1141
3. How to check that?
4. `/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin`
5. No, `/QOpenSys/usr/bin/qsh` returns to bash without any output. It does not open a new shell, as one my expect.

Sorry, but I must close for today.

**Comment by worksofliam** [comment] 2021-03-07 20:46
@tools400 I think I will close this issue (as it's not related to the extension), but for your question checking which bash you're using: where did you set your default shell?

**Closed** 2021-03-07 20:47 UTC
Labels: discussion
